_wandb:
    value:
        cli_version: 0.23.0
        e:
            88ny1ycs62heactp3cox0x7zhzu2qmc5:
                apple:
                    ecpuCores: 2
                    gpuCores: 14
                    memoryGb: 16
                    name: Apple M1 Pro
                    pcpuCores: 6
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "7516192768"
                codePath: /Users/conquerormikrokosmos/Downloads/LAPTOP MAC/MYUNIVERSITY/ĐẠI HỌC QUỐC GIA TPHCM/ĐH KHOA HỌC TỰ NHIÊN/NĂM 4/HKI/Intelligent Data Analysis/Chatbot_Extension/model_baseline.ipynb
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "409669525504"
                email: nguyenanhkhoi0608@gmail.com
                executable: /Users/conquerormikrokosmos/Downloads/LAPTOP MAC/MYUNIVERSITY/ĐẠI HỌC QUỐC GIA TPHCM/ĐH KHOA HỌC TỰ NHIÊN/NĂM 4/HKI/Intelligent Data Analysis/Chatbot_Extension/.venv/bin/python
                git:
                    commit: 71f412ab94b5d2f477764c5178a7a12a36adb905
                    remote: https://github.com/dihungg/Chatbot_Extension.git
                host: 192.168.1.109
                memory:
                    total: "17179869184"
                os: macOS-26.0.1-arm64-arm-64bit
                program: /Users/conquerormikrokosmos/Downloads/LAPTOP MAC/MYUNIVERSITY/ĐẠI HỌC QUỐC GIA TPHCM/ĐH KHOA HỌC TỰ NHIÊN/NĂM 4/HKI/Intelligent Data Analysis/Chatbot_Extension/model_baseline.ipynb
                python: CPython 3.10.19
                root: /Users/conquerormikrokosmos/Downloads/LAPTOP MAC/MYUNIVERSITY/ĐẠI HỌC QUỐC GIA TPHCM/ĐH KHOA HỌC TỰ NHIÊN/NĂM 4/HKI/Intelligent Data Analysis/Chatbot_Extension
                startedAt: "2025-11-27T13:20:47.156610Z"
                writerId: 88ny1ycs62heactp3cox0x7zhzu2qmc5
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 5
                - 7
                - 35
                - 53
            "2":
                - 5
                - 7
                - 35
                - 53
            "3":
                - 2
                - 13
                - 61
            "4": 3.10.19
            "5": 0.23.0
            "8":
                - 1
                - 2
            "12": 0.23.0
            "13": darwin-arm64
direction:
    value:
        - MAXIMIZE
